### ISSUE TITLE
После разворачивания свернутого приложения открывается список товаров от другой точки

### ISSUE THREAD

**Issue by nataliaromanenko** [antashev/FindGoods#19]
1. Выбрать точку 1
2. Свернуть приложение
3. Развернуть приложение - на экране список точек
4. Выбрать точку 2
Результат: открывается список товаров точки 1
Ожидаемый результат: открывается список точки 2, либо нет перехода к экрана выбора точки

**Comment by antashev** [comment]
исправлено в версии 1.3
