### ISSUE TITLE
Белый экран после запрета использования камеры

### ISSUE THREAD

**Issue by nataliaromanenko** [antashev/FindGoods#20]
Если в диалоге получения разрешения на использование камеры запретить  использование, приложение зависает с белым экраном
![device-2018-05-16-161724](https://user-images.githubusercontent.com/16988298/40108612-9f334f8e-5925-11e8-83ed-ccb03f1f7729.gif)

**Comment by antashev** [comment]
завершаю экран если пользователь не предоставил доступ к камере
