### ISSUE TITLE
Не устанавливается релизная версия приложения

### ISSUE THREAD

**Issue by nataliaromanenko** [antashev/FindGoods#5]
C:\Users\nromanenko\Downloads\app-rc-release-unsigned.apk: 1 file pushed. 5.8 MB/s (3532923 bytes in 0.581s)
        pkg: /data/local/tmp/app-rc-release-unsigned.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

**Comment by antashev** [comment]
cделал подпись приложения ключом разработчика. На ci теперь не собирается(починю потом) Зато релизная версия появилась в магазине тестовых устройств
