### ISSUE TITLE
При вводе цены/мин. цены не стирается 0.00

### ISSUE THREAD

**Issue by nataliaromanenko** [antashev/FindGoods#8]
Сейчас если в поле "Цена" или "Минимальная цена" ввести какое-то число, то "0.00" не сотрется, введенные цифры будут дописаны.
Можно сделать так: если в эти поля ввести какое-то число, то "0.00", указанное по умолчанию, стирается, а поле заполняется введенным значением.

**Comment by antashev** [comment]
сделал начальное значение цены и минимальной цены как hint
